Fixed the suggested issues
tanveerisonline/personal-portfolio-website pull request #2
Opened 2022-11-09 21:11 UTC by tanveerisonline

### Following are the things that have been done in this project:

1. Added changes to HTML and CSS. 
2. Added changes to CSS to follow the Dry principle (Don't Repeat Yourself Principle).
3. Fixed issues related to responsiveness.
4. Fixed the broken MIT license link.
5. Followed HTML and CSS best practices.

2022-11-10 09:38 UTC, ahmetbozaci requested changes
@tanveerisonline  ✋🏼 
### This is a manual review
### Please don't open a new branch for changes, continue with this branch(my-portfolio)   ⚠️ ⚠️ 
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️ 
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
___ 

### 💯  Highlights 💯
- You follow the DRY CSS principles.
___

### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-11-10 09:38 UTC, ahmetbozaci commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] This link is still broken. To make a professional readme file please fix it.

2022-11-10 09:38 UTC, ahmetbozaci commented on styles.css
> +  font-size: 18px;
- Well done apply the DRY CSS principles 💯

2022-11-10 09:38 UTC, ahmetbozaci commented on README.md
> +### Deployment
### OPTIONAL
- [ ] I recommend you fill many sections as you can. But if you won't fill sections better to delete them. It is important to make a professional readme file.

2022-11-10 09:38 UTC, ahmetbozaci commented on index.html
> +          <a href="#" target="_parent" class="logo f-size">Tanveer Ahmad</a>
- [ ] Website is still not responsive below 768px width remaining the same which is not good for tablets. Kindly fix this

1. You can see the container class has a width. That's why the remaining 375px. But not only this class. Please find which classes have a width and delete them. If the page is still not responsive kindly find which CSS makes happen that and fix it.

1. Background image should responsive too.

![image](https://user-images.githubusercontent.com/38635158/201053078-a50a95fa-b686-4118-8331-586fe6e82ef1.png)
___
After closed width
![image](https://user-images.githubusercontent.com/38635158/201054211-1b5aed86-f202-42aa-8520-eca9f263a1ea.png)

2022-11-12 11:38 UTC, medaminedev66 approved these changes
Hi @tanveerisonline 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- The page is responsive
- Your design looks great and matches the Figma design

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 11:57 UTC, merged